USE helpdesk_db;


INSERT INTO usuarios (username, password) VALUES 
('admin', '$2y$10$wKxN7CkW9p0mC7Rj9G3yUeE7v1V2w3x4y5z6a7b8c9d0e1f2g3h4i');


INSERT INTO incidencias (titulo, descripcion, prioridad, estado) VALUES
('Error de conexión en switch planta 1', 'Los equipos del departamento de compras no obtienen IP.', 'Alta', 'Abierta'),
('Fallo de tóner en impresora de dirección', 'La impresora principal mancha las hojas al imprimir.', 'Media', 'Abierta'),
('Actualización de ERP mensual', 'Programar ventana de mantenimiento del software el viernes a las 22:00.', 'Baja', 'Cerrada'),
('Pantalla azul en PC de recepción', 'El equipo se reinicia aleatoriamente mostrando el error WHEA.', 'Alta', 'Abierta'),
('Configuración de VPN para teletrabajo', 'Dar de alta al nuevo empleado de marketing en el servidor OpenVPN.', 'Media', 'Cerrada'),
('Microcortes en el enlace de fibra', 'El router principal pierde sincronía durante unos segundos.', 'Alta', 'Abierta'),
('Instalación de antivirus en servidor local', 'Renovar la licencia corporativa en el servidor de archivos.', 'Baja', 'Abierta'),
('Bloqueo de cuenta de correo corporativo', 'El usuario superó los intentos de login en Outlook.', 'Baja', 'Cerrada'),
('Lentitud en la base de datos de pruebas', 'Los índices parecen corruptos tras la última migración.', 'Media', 'Abierta'),
('Sustitución de cable de red dañado', 'El cable del puesto 14 está pelado y pierde paquetes.', 'Baja', 'Abierta'),
('Error de certificado SSL en la intranet', 'El navegador muestra aviso de sitio no seguro.', 'Alta', 'Abierta'),
('Configurar copia de seguridad en NAS', 'Añadir la carpeta de proyectos al script de backup diario.', 'Media', 'Abierta'),
('Limpieza de polvo en servidores de rack', 'Mantenimiento preventivo anual en el CPD.', 'Baja', 'Cerrada'),
('Fallo en el sistema de alimentación ininterrumpida (SAI)', 'La batería del rack de comunicaciones está agotada.', 'Alta', 'Abierta'),
('Petición de ratón y teclado inalámbrico', 'Sustitución por desgaste para el puesto de administración.', 'Baja', 'Cerrada'),
('Problema con los permisos en la carpeta compartida', 'El equipo de RRHH no puede escribir en la carpeta compartida.', 'Media', 'Abierta'),
('Caída total del servidor web interno', 'El servicio Apache se detuvo de forma inesperada.', 'Alta', 'Abierta'),
('Configurar firma corporativa en Thunderbird', 'Añadir nueva plantilla HTML al departamento de ventas.', 'Baja', 'Cerrada'),
('Mapear unidad de red en portátil nuevo', 'Conectar la letra Z: al servidor de datos del usuario.', 'Baja', 'Abierta'),
('Sustitución de disco duro dañado en RAID', 'El disco 3 del servidor principal muestra estado crítico.', 'Alta', 'Abierta'),
('Instalar entorno de desarrollo PHP', 'Configurar Xdebug en el equipo del nuevo desarrollador.', 'Media', 'Abierta'),
('Fallo de cobertura WiFi en sala de juntas', 'El punto de acceso pierde potencia intermitentemente.', 'Media', 'Abierta'),
('Cambio de contraseña caducada', 'El director general no recuerda su clave de acceso.', 'Alta', 'Cerrada'),
('Revisar reglas del cortafuegos corporativo', 'Bloquear accesos no autorizados al puerto 22 desde el exterior.', 'Alta', 'Abierta'),
('Soporte para configurar correo en móvil', 'Sincronizar cuenta IMAP en el smartphone de empresa.', 'Baja', 'Cerrada'),
('Bloqueo de SPAM entrante', 'Ajustar filtros de correo para evitar emails de phishing.', 'Media', 'Abierta'),
('Instalación de parches de seguridad en Windows', 'Actualizar los equipos de la oficina técnica.', 'Baja', 'Cerrada'),
('Fallo en el lector de tarjetas de la entrada', 'Los empleados no pueden fichar con su acreditación.', 'Alta', 'Abierta'),
('Petición de doble monitor para diseño', 'Instalar segunda pantalla de 24 pulgadas en el puesto 5.', 'Baja', 'Abierta'),
('Ruido extraño en ventilador de fuente de alimentación', 'El PC de contabilidad hace demasiado ruido al encender.', 'Media', 'Abierta'),
('Error de sincronización con la nube', 'Los archivos locales no se suben al almacenamiento remoto.', 'Media', 'Abierta'),
('Configurar teléfono IP de secretaría', 'Asignar la extensión 102 al terminal físico nuevo.', 'Baja', 'Cerrada'),
('Caída de la línea telefónica analógica', 'No se pueden recibir llamadas externas en la centralita.', 'Alta', 'Abierta'),
('Migración de base de datos MariaDB', 'Exportar tablas antiguas al nuevo servidor de desarrollo.', 'Media', 'Cerrada'),
('Error de compilación en script de automatización', 'El script de Python falla al parsear los logs diarios.', 'Media', 'Abierta'),
('Renovación de licencias de Office 365', 'Aplicar los nuevos códigos de activación anual.', 'Baja', 'Cerrada'),
('PC de almacén no enciende', 'Posible fallo en la placa base tras tormenta eléctrica.', 'Alta', 'Abierta'),
('Configurar acceso SSH por clave pública', 'Eliminar acceso por contraseña en el servidor de pruebas.', 'Alta', 'Abierta'),
('Fallo de visualización en proyector', 'La imagen se muestra en tonos amarillos en la sala 1.', 'Media', 'Abierta'),
('Problemas de impresión a doble cara', 'La fotocopiadora atasca el papel en modo dúplex.', 'Media', 'Cerrada'),
('Configuración de alertas en Grafana', 'Añadir aviso al correo cuando el uso de CPU supere el 90%.', 'Baja', 'Abierta'),
('Desinstalar software no autorizado', 'Retirar programas de descarga P2P encontrados en un PC.', 'Media', 'Cerrada'),
('Optimizar espacio en disco de servidor', 'Eliminar logs antiguos de más de un año de antigüedad.', 'Baja', 'Abierta'),
('Error en pasarela de pago web', 'Los clientes reportan fallos al validar el código de seguridad.', 'Alta', 'Abierta'),
('Recuperar archivo borrado por error', 'Restaurar documento de texto desde la copia de seguridad de ayer.', 'Media', 'Cerrada'),
('Configurar VLAN para invitados', 'Aislar las conexiones del WiFi público de la red local.', 'Alta', 'Abierta'),
('Teclas atascadas en portátil corporativo', 'Sustituir teclado de portátil por vertido de líquido.', 'Media', 'Abierta'),
('Actualizar firmware de switches core', 'Aplicar parche del fabricante para mitigar vulnerabilidad.', 'Alta', 'Abierta'),
('Error de volcado de memoria (Dump)', 'El servidor de aplicaciones web genera archivos muy pesados.', 'Media', 'Abierta'),
('Petición de webcam para videoconferencias', 'Entregar accesorio para reuniones de teletrabajo.', 'Baja', 'Cerrada'),
('Fallo en el termostato del CPD', 'La temperatura del rack ha subido a 26 grados.', 'Alta', 'Abierta'),
('Configurar repositorio Git interno', 'Crear proyecto vacío y dar permisos al equipo de desarrollo.', 'Baja', 'Cerrada'),
('Error 404 persistente en imágenes del sitio', 'Las rutas relativas se rompieron tras el despliegue.', 'Media', 'Abierta');
